theme = "solarized_dark_improved"
[editor]
auto-completion = false
cursorline = true
middle-click-paste = false
rulers = [80]
true-color = true
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[editor.gutters]
layout = [ "diagnostics", "spacer", "diff" ]
[editor.statusline]
right = [ "diagnostics", "register", "position", "file-encoding" ]
[editor.inline-diagnostics]
cursor-line = "warning"
